### ISSUE TITLE
Add old-stats metrics

### ISSUE THREAD

**Issue by misi** [ObserveRTC/client-monitor-js#2]
Add old stat metrics with all goog prefixed metrics

**Comment by balazskreith** [comment]
The schema for clientSample should be based on the actual draft I think. If any browser-specific implementation or metric is relevant or useful we can report it as extensionStats for example like this:
```
monitor.events.onStatsCollected(rawStatsArray => {
  // rawStatsArray is an array of stats polled from peer connections, thus they should contain the metrics you are looking for
  const browserSpecificMetrics = {} // make a magic to select the metrics you want to report
  
  // send it as extension stats
  monitor.addExtensionStats({
    name: "BROWSER_SPECIFIC_METRICS",
    payload: JSON.stringify(browserSpecificMetrics)
  });
```

In that way you will end up having them as extension stats in your database.

**Comment by balazskreith** [comment]
as mentioned above any kind of browser specific stats can be added as extension-stats. As client-monitor no longer responsible for transport, the application do the signalling to the stats-collecting server can accept browser-spcecific stats too.
