### ISSUE TITLE
sometimes client collected latency giving abnormal values

### ISSUE THREAD

**Issue by deepso7** [ObserveRTC/client-monitor-js#24]
`monitor.storage.avgRttInS`

<img width="261" alt="image" src="https://github.com/ObserveRTC/client-monitor-js/assets/34184939/1b7efa42-0273-47a9-bb40-1c9ce56da0f7">

**Comment by balazskreith** [comment]
hopefully fixed in f1698d666f179bdc986384d695a6b67d58308009
