### ISSUE TITLE
Client collected metrics are always empty

### ISSUE THREAD

**Issue by rostamiani** [ObserveRTC/client-monitor-js#9]
I just Added a monitor to my Mediasoup project, but samples are always empty
I Added webcam streaming and executed this function:
```js
let monitor;
function observeRtcStart(device) {
  monitor = createClientMonitor({
    collectingPeriodInMs: 1000,
    samplingPeriodInMs: 2000,
    sendingPeriodInMs: 60000
  });
  monitor.setRoomId(1234);
  monitor.collectors.addMediasoupDevice(device);

  monitor.events.onSampleCreated((e) => console.log('sample created', e));
  monitor.events.onConnected((e) => console.log('connected', e));
  monitor.events.onStatsCollected((e) => console.log('collected', e));
}
```

And the output is empty:
![image](https://user-images.githubusercontent.com/1157108/208233947-2e6bf01f-435f-40c8-b8b2-e42d0610f94d.png)

And this is the `about:webrtc` page:
![image](https://user-images.githubusercontent.com/1157108/208233985-6ec44b08-d128-4833-9f1b-3eaa5127c63f.png)

**Comment by balazskreith** [comment]
Hello.

Thank you for raising the issue. 
Have you added the monitor before you create the transports, or after?

Asking because the mediasoup integration hooks the device `newtransport` events at the moment you add it. if you created a transport before and then add the device to the client monitor it will not get the transport you created before.

**Comment by balazskreith** [comment]
@rostamiani can you check if it solves the issue you have? 

In any case adding it to this issue https://github.com/ObserveRTC/client-monitor-js/pull/10 as it makes 'addTransport' method from mediasoup stats collector to be public so you can add your transport after it is created

**Comment by rostamiani** [comment]
Thanks...
I Added the transport after addMediasoupDevice and the problem solved.
It's a good idea to add it to the docs if it's not already mentioned

**Comment by balazskreith** [comment]
https://github.com/ObserveRTC/client-monitor-js/tree/version-1-3-1, and thanks again for raising the issue!
